namespace EFT.Ballistics;

public enum MaterialType
{
	Asphalt = 1,
	Body = 2,
	Cardboard = 3,
	Chainfence = 4,
	Concrete = 5,
	Fabric = 6,
	GarbageMetal = 7,
	GarbagePaper = 8,
	GenericSoft = 9,
	Glass = 10,
	GlassShattered = 11,
	Grate = 12,
	GrassHigh = 13,
	GrassLow = 14,
	Gravel = 15,
	MetalThin = 16,
	MetalThick = 17,
	Mud = 18,
	Pebbles = 19,
	Plastic = 20,
	Stone = 21,
	Soil = 22,
	SoilForest = 23,
	Tile = 24,
	Water = 25,
	WaterPuddle = 26,
	WoodThin = 27,
	WoodThick = 28,
	Tyre = 29,
	Rubber = 30,
	GenericHard = 31,
	BodyArmor = 32,
	Swamp = 33,
	Helmet = 34,
	GlassVisor = 35,
	HelmetRicochet = 36,
	MetalNoDecal = 37,
	None = 0
}
