public enum ECharacterWeaponBones
{
	HumanLCollarbone,
	HumanRCollarbone,
	HumanLPalm,
	HumanRPalm,
	Weapon_root_anim,
	Weapon_root,
	Bend_Goal_Left,
	Bend_Goal_Right,
	weapon_R_hand_marker,
	weapon_R_IK_marker,
	weapon_L_hand_marker,
	weapon_L_IK_marker,
	Camera_animated,
	weapon,
	HumanLUpperarm,
	HumanLForearm1,
	HumanRUpperarm,
	HumanRForearm1,
	weapon_vest_IK_marker,
	prop
}
