namespace EFT.Communications;

public enum ENotificationType
{
	[_E618("ping")]
	Ping,
	[_E618("channel_deleted")]
	ChannelDeleted,
	[_E618("trader_supply")]
	TraderSupply,
	[_E618("groupMatchInviteAccept")]
	GroupMatchInviteAccept,
	[_E618("groupMatchInviteDecline")]
	GroupMatchInviteDecline,
	[_E618("groupMatchWasRemoved")]
	GroupMatchWasRemoved,
	[_E618("groupMatchInviteSend")]
	GroupMatchInviteSend,
	[_E618("groupMatchInviteCancel")]
	GroupMatchInviteCancel,
	[_E618("groupMatchInviteExpired")]
	GroupMatchInviteExpired,
	[_E618("groupMatchLeaderChanged")]
	GroupMatchLeaderChanged,
	[_E618("groupMatchUserLeave")]
	GroupMatchUserLeave,
	[_E618("groupMaxCountReached")]
	GroupMaxCountReached,
	[_E618("groupMatchStartGame")]
	GroupMatchStartGame,
	[_E618("groupMatchRaidSettings")]
	GroupMatchRaidSettings,
	[_E618("groupMatchRaidReady")]
	GroupMatchRaidReady,
	[_E618("groupMatchRaidNotReady")]
	GroupMatchRaidNotReady,
	[_E618("groupMatchAbort")]
	GroupMatchAbort,
	[_E618("groupMatchUserHasBadVersion")]
	WrongMajorVersion,
	[_E618("new_message")]
	ChatMessageReceived,
	[_E618("youAreRemovedFromFriendList")]
	RemovedFromFriendsList,
	[_E618("friendListNewRequest")]
	FriendsListNewRequest,
	[_E618("friendListRequestCancel")]
	FriendsListRequestCanceled,
	[_E618("tournamentWarning")]
	TournamentWarning,
	[_E618("friendListRequestDecline")]
	FriendsListDecline,
	[_E618("friendListRequestAccept")]
	FriendsListAccept,
	[_E618("groupMatchYouWasKicked")]
	YouWasKickedFromDialogue,
	[_E618("youAreAddToIgnoreList")]
	YouWereAddedToIgnoreList,
	[_E618("youAreRemoveFromIgnoreList")]
	YouWereRemovedToIgnoreList,
	RagfairOfferSold,
	RagfairRatingChange,
	RagfairNewRating,
	ForceLogout,
	InGameBan,
	InGameUnBan,
	Hideout,
	TraderStanding,
	ProfileLevel,
	SkillPoints,
	HideoutAreaLevel,
	AssortmentUnlockRule,
	ExamineItems,
	ExamineAllItems,
	TraderSalesSum,
	UnlockTrader,
	ProfileLockTimer,
	MasteringSkill,
	ProfileExperienceDelta,
	TraderStandingDelta,
	TraderSalesSumDelta,
	SkillPointsDelta,
	MasteringSkillDelta,
	[_E618("userMatched")]
	UserMatched,
	[_E618("userMatchOver")]
	UserMatchOver,
	[_E618("userConfirmed")]
	UserConfirmed
}
