namespace EFT;

public enum EBuffId
{
	[_E618("None")]
	None,
	[_E618("EnduranceBuffEnduranceInc")]
	EnduranceBuffEnduranceInc,
	[_E618("EnduranceBuffJumpCostRed")]
	EnduranceBuffJumpCostRed,
	[_E618("EnduranceBuffBreathTimeInc")]
	EnduranceBuffBreathTimeInc,
	[_E618("EnduranceBuffRestorationTimeRed")]
	EnduranceBuffRestorationTimeRed,
	[_E618("EnduranceBreathElite")]
	EnduranceBreathElite,
	[_E618("EnduranceHands")]
	EnduranceHands,
	[_E618("StrengthBuffLiftWeightInc")]
	StrengthBuffLiftWeightInc,
	[_E618("StrengthBuffSprintSpeedInc")]
	StrengthBuffSprintSpeedInc,
	[_E618("StrengthBuffJumpHeightInc")]
	StrengthBuffJumpHeightInc,
	[_E618("StrengthBuffThrowDistanceInc")]
	StrengthBuffThrowDistanceInc,
	[_E618("StrengthBuffMeleePowerInc")]
	StrengthBuffMeleePowerInc,
	[_E618("StrengthBuffElite")]
	StrengthBuffElite,
	[_E618("StrengthBuffMeleeCrits")]
	StrengthBuffMeleeCrits,
	[_E618("StrengthBuffAim")]
	StrengthBuffAim,
	[_E618("VitalityBuffBleedChanceRed")]
	VitalityBuffBleedChanceRed,
	[_E618("VitalityBuffSurviobilityInc")]
	VitalityBuffSurviobilityInc,
	[_E618("VitalityBuffRegeneration")]
	VitalityBuffRegeneration,
	[_E618("VitalityBuffBleedStop")]
	VitalityBuffBleedStop,
	[_E618("HealthBreakChanceRed")]
	HealthBreakChanceRed,
	[_E618("HealthOfflineRegenerationInc")]
	HealthOfflineRegenerationInc,
	[_E618("HealthEnergy")]
	HealthEnergy,
	[_E618("HealthHydration")]
	HealthHydration,
	[_E618("HealthEliteAbsorbDamage")]
	HealthEliteAbsorbDamage,
	[_E618("HealthElitePosion")]
	HealthElitePosion,
	[_E618("StressPainChance")]
	StressPainChance,
	[_E618("StressTremor")]
	StressTremor,
	[_E618("StressBerserk")]
	StressBerserk,
	[_E618("MetabolismRatioPlus")]
	MetabolismRatioPlus,
	[_E618("MetabolismEnergyExpenses")]
	MetabolismEnergyExpenses,
	[_E618("MetabolismPhysicsForget")]
	MetabolismPhysicsForget,
	[_E618("MetabolismPhysicsForget2")]
	MetabolismPhysicsForget2,
	[_E618("MetabolismEliteBuffNoDyhydration")]
	MetabolismEliteBuffNoDyhydration,
	[_E618("MetabolismEliteNoForget")]
	MetabolismEliteNoForget,
	[_E618("PerceptionHearing")]
	PerceptionHearing,
	[_E618("PerceptionFov")]
	PerceptionFov,
	[_E618("PerceptionLootDot")]
	PerceptionLootDot,
	[_E618("PerceptionmEliteNoIdea")]
	PerceptionmEliteNoIdea,
	[_E618("IntellectLearningSpeed")]
	IntellectLearningSpeed,
	[_E618("IntellectWeaponMaintance")]
	IntellectWeaponMaintance,
	[_E618("IntellectEliteNaturalLearner")]
	IntellectEliteNaturalLearner,
	[_E618("IntellectEliteAmmoCounter")]
	IntellectEliteAmmoCounter,
	[_E618("IntellectEliteContainerScope")]
	IntellectEliteContainerScope,
	[_E618("IntellectRepairPointsCostReduction")]
	IntellectRepairPointsCostReduction,
	[_E618("AttentionLootSpeed")]
	AttentionLootSpeed,
	[_E618("AttentionRareLoot")]
	AttentionRareLoot,
	[_E618("AttentionEliteLuckySearch")]
	AttentionEliteLuckySearch,
	[_E618("AttentionEliteExtraLootExp")]
	AttentionEliteExtraLootExp,
	[_E618("MagDrillsLoadSpeed")]
	MagDrillsLoadSpeed,
	[_E618("MagDrillsUnloadSpeed")]
	MagDrillsUnloadSpeed,
	[_E618("MagDrillsInventoryCheckSpeed")]
	MagDrillsInventoryCheckSpeed,
	[_E618("MagDrillsInventoryCheckAccuracy")]
	MagDrillsInventoryCheckAccuracy,
	[_E618("MagDrillsInstantCheck")]
	MagDrillsInstantCheck,
	[_E618("MagDrillsLoadProgression")]
	MagDrillsLoadProgression,
	[_E618("CharismaBuff1")]
	CharismaBuff1,
	[_E618("CharismaBuff2")]
	CharismaBuff2,
	[_E618("CharismaEliteBuff1")]
	CharismaEliteBuff1,
	[_E618("CharismaEliteBuff2")]
	CharismaEliteBuff2,
	[_E618("CharismaDailyQuestsRerollDiscount")]
	CharismaDailyQuestsRerollDiscount,
	[_E618("CharismaHealingDiscount")]
	CharismaHealingDiscount,
	[_E618("CharismaInsuranceDiscount")]
	CharismaInsuranceDiscount,
	[_E618("CharismaExfiltrationDiscount")]
	CharismaExfiltrationDiscount,
	[_E618("CharismaScavCaseDiscount")]
	CharismaScavCaseDiscount,
	[_E618("CharismaFenceReducePenalty")]
	CharismaFenceRepPenaltyReduction,
	[_E618("CharismaAdditionalDailyQuests")]
	CharismaAdditionalDailyQuests,
	[_E618("MemoryMentalForget1")]
	MemoryMentalForget1,
	[_E618("MemoryMentalForget2")]
	MemoryMentalForget2,
	[_E618("MemoryEliteMentalNoDegradation")]
	MemoryEliteMentalNoDegradation,
	[_E618("WeaponReloadBuff")]
	WeaponReloadBuff,
	[_E618("WeaponRecoilBuff")]
	WeaponRecoilBuff,
	[_E618("WeaponSwapBuff")]
	WeaponSwapBuff,
	[_E618("DrawSpeed")]
	DrawSpeed,
	[_E618("DrawElite")]
	DrawElite,
	[_E618("DrawTremor")]
	DrawTremor,
	[_E618("DrawSound")]
	DrawSound,
	[_E618("AimMasterElite")]
	AimMasterElite,
	[_E618("AimMasterWiggle")]
	AimMasterWiggle,
	[_E618("AimMasterSpeed")]
	AimMasterSpeed,
	[_E618("RecoilControlImprove")]
	RecoilControlImprove,
	[_E618("RecoilControlElite")]
	RecoilControlElite,
	[_E618("CovertMovementSoundVolume")]
	CovertMovementSoundVolume,
	[_E618("ProneMovementSpeed")]
	ProneMovementSpeed,
	[_E618("ProneMovementVolume")]
	ProneMovementVolume,
	[_E618("ProneMovementElite")]
	ProneMovementElite,
	[_E618("TroubleFixing")]
	TroubleFixing,
	[_E618("TroubleFixingAmmoElite")]
	TroubleFixingAmmoElite,
	[_E618("TroubleFixingExamineMalfElite")]
	TroubleFixingExamineMalfElite,
	[_E618("WeaponErgonomicsBuff")]
	WeaponErgonomicsBuff,
	[_E618("WeaponDoubleMastering")]
	WeaponDoubleMastering,
	[_E618("WeaponDoubleActionRecoilReduceBuff")]
	WeaponDoubleActionRecoilReduceBuff,
	[_E618("WeaponStiffHands")]
	WeaponStiffHands,
	[_E618("ThrowingStrengthBuff")]
	ThrowingStrengthBuff,
	[_E618("ThrowingEnergyExpenses")]
	ThrowingEnergyExpenses,
	[_E618("ThrowingWeaponsBuffElite")]
	ThrowingWeaponsBuffElite,
	[_E618("CovertMovementSpeed")]
	CovertMovementSpeed,
	[_E618("CovertMovementElite")]
	CovertMovementElite,
	[_E618("CovertMovementLoud")]
	CovertMovementLoud,
	[_E618("CovertMovementEquipment")]
	CovertMovementEquipment,
	[_E618("SearchSpeed")]
	SearchSpeed,
	[_E618("SearchDouble")]
	SearchDouble,
	[_E618("SurgeryReducePenalty")]
	SurgeryReducePenalty,
	[_E618("SurgerySpeed")]
	SurgerySpeed,
	[_E618("HideoutResourceConsumption")]
	HideoutResourceConsumption,
	[_E618("HideoutZoneBonusBoost")]
	HideoutZoneBonusBoost,
	[_E618("HideoutExtraSlots")]
	HideoutExtraSlots,
	[_E618("CraftingElite")]
	CraftingElite,
	[_E618("CraftingSingleTimeReduce")]
	CraftingSingleTimeReduce,
	[_E618("CraftingContinueTimeReduce")]
	CraftingContinueTimeReduce,
	[_E618("MetabolismPoisonTime")]
	MetabolismPoisonTime,
	[_E618("MetabolismMiscDebuffTime")]
	MetabolismMiscDebuffTime,
	[_E618("ImmunityMiscEffects")]
	ImmunityMiscEffects,
	[_E618("ImmunityPoisonBuff")]
	ImmunityPoisonBuff,
	[_E618("ImmunityPainKiller")]
	ImmunityPainKiller,
	[_E618("ImmunityPoisonChance")]
	ImmunityPoisonChance,
	[_E618("ImmunityMiscEffectsChance")]
	ImmunityMiscEffectsChance,
	[_E618("WeaponDurabilityLossOnShotReduce")]
	WeaponDurabilityLossOnShotReduce,
	[_E618("WearAmountRepairGunsReducePerLevel")]
	WearAmountRepairGunsReducePerLevel,
	[_E618("WearChanceRepairGunsReduceEliteLevel")]
	WearChanceRepairGunsReduceEliteLevel,
	[_E618("TroubleFixingMagElite")]
	TroubleFixingMagElite,
	[_E618("TroubleFixingDurElite")]
	TroubleFixingDurElite,
	[_E618("LightVestMoveSpeedPenaltyReduction")]
	LightVestMoveSpeedPenaltyReduction,
	[_E618("LightVestMeleeWeaponDamageReduction")]
	LightVestMeleeWeaponDamageReduction,
	[_E618("LightVestRepairDegradationReduction")]
	LightVestRepairDegradationReduction,
	[_E618("LightVestBleedingProtection")]
	LightVestBleedingProtection,
	[_E618("LightVestDeteriorationChanceOnRepairReduce")]
	LightVestDeteriorationChanceOnRepairReduce,
	[_E618("HeavyVestMoveSpeedPenaltyReduction")]
	HeavyVestMoveSpeedPenaltyReduction,
	[_E618("HeavyVestBluntThroughputDamageReduction")]
	HeavyVestBluntThroughputDamageReduction,
	[_E618("HeavyVestRepairDegradationReduction")]
	HeavyVestRepairDegradationReduction,
	[_E618("HeavyVestNoBodyDamageDeflectChance")]
	HeavyVestNoBodyDamageDeflectChance,
	[_E618("HeavyVestDeteriorationChanceOnRepairReduce")]
	HeavyVestDeteriorationChanceOnRepairReduce
}
