namespace EFT;

public enum ESkillId : byte
{
	[_E618("Endurance")]
	Endurance,
	[_E618("Strength")]
	Strength,
	[_E618("Vitality")]
	Vitality,
	[_E618("Health")]
	Health,
	[_E618("StressResistance")]
	StressResistance,
	[_E618("Metabolism")]
	Metabolism,
	[_E618("Immunity")]
	Immunity,
	[_E618("Perception")]
	Perception,
	[_E618("Intellect")]
	Intellect,
	[_E618("Attention")]
	Attention,
	[_E618("Charisma")]
	Charisma,
	[_E618("Memory")]
	Memory,
	[_E618("MagDrills")]
	MagDrills,
	[_E618("Pistol")]
	Pistol,
	[_E618("Revolver")]
	Revolver,
	[_E618("SMG")]
	SMG,
	[_E618("Assault")]
	Assault,
	[_E618("Shotgun")]
	Shotgun,
	[_E618("Sniper")]
	Sniper,
	[_E618("LMG")]
	LMG,
	[_E618("HMG")]
	HMG,
	[_E618("Launcher")]
	Launcher,
	[_E618("AttachedLauncher")]
	AttachedLauncher,
	[_E618("Throwing")]
	Throwing,
	[_E618("Misc")]
	Misc,
	[_E618("Melee")]
	Melee,
	[_E618("DMR")]
	DMR,
	[_E618("DrawMaster")]
	DrawMaster,
	[_E618("AimMaster")]
	AimMaster,
	[_E618("RecoilControl")]
	RecoilControl,
	[_E618("TroubleShooting")]
	TroubleShooting,
	[_E618("Sniping")]
	Sniping,
	[_E618("CovertMovement")]
	CovertMovement,
	[_E618("ProneMovement")]
	ProneMovement,
	[_E618("FirstAid")]
	FirstAid,
	[_E618("FieldMedicine")]
	FieldMedicine,
	[_E618("Surgery")]
	Surgery,
	[_E618("LightVests")]
	LightVests,
	[_E618("HeavyVests")]
	HeavyVests,
	[_E618("WeaponModding")]
	WeaponModding,
	[_E618("AdvancedModding")]
	AdvancedModding,
	[_E618("NightOps")]
	NightOps,
	[_E618("SilentOps")]
	SilentOps,
	[_E618("Lockpicking")]
	Lockpicking,
	[_E618("Search")]
	Search,
	[_E618("WeaponTreatment")]
	WeaponTreatment,
	[_E618("Freetrading")]
	Freetrading,
	[_E618("Auctions")]
	Auctions,
	[_E618("Cleanoperations")]
	Cleanoperations,
	[_E618("Barter")]
	Barter,
	[_E618("Shadowconnections")]
	Shadowconnections,
	[_E618("Taskperformance")]
	Taskperformance,
	[_E618("BearAssaultoperations")]
	BearAssaultoperations,
	[_E618("BearAuthority")]
	BearAuthority,
	[_E618("BearAksystems")]
	BearAksystems,
	[_E618("BearHeavycaliber")]
	BearHeavycaliber,
	[_E618("BearRawpower")]
	BearRawpower,
	[_E618("UsecArsystems")]
	UsecArsystems,
	[_E618("UsecDeepweaponmodding")]
	UsecDeepweaponmodding,
	[_E618("UsecLongrangeoptics")]
	UsecLongrangeoptics,
	[_E618("UsecNegotiations")]
	UsecNegotiations,
	[_E618("UsecTactics")]
	UsecTactics,
	[_E618("\ue162")]
	BotReload,
	[_E618("BotSound")]
	BotSound,
	[_E618("AimDrills")]
	AimDrills,
	[_E618("HideoutManagement")]
	HideoutManagement,
	[_E618("Crafting")]
	Crafting
}
